version: '3.7'

services:
    server:
        build: .
        ports: 
            - 3000:3000
        env_file:
            - .env.server
        depends_on:
            - neo4j 
    neo4j:
        image: neo4j:latest
        ports: 
            - 7474:7474
            - 7687:7687
        volumes:
            - neo4j_data:/data/
        env_file:
            - .env.neo4j

volumes:
    neo4j_data:
